export const types = {
	CHANGE_PATH: 'CHANGE_PATH',
	FETCH_CURRENT_VIDEO_REQUEST: 'FETCH_CURRENT_VIDEO_REQUEST',
	FETCH_CURRENT_VIDEO_SUCCESS: 'FETCH_CURRENT_VIDEO_SUCCESS',
	FETCH_CURRENT_VIDEO_ERROR: 'FETCH_CURRENT_VIDEO_ERROR',
	FETCH_VIDEO_LIST_REQUEST: 'FETCH_VIDEO_LIST_REQUEST',
	FETCH_VIDEO_LIST_SUCCESS: 'FETCH_VIDEO_LIST_SUCCESS',
	FETCH_VIDEO_LIST_ERROR: 'FETCH_VIDEO_LIST_ERROR',
	FETCH_DEVICE_LIST_REQUEST: 'FETCH_DEVICE_LIST_REQUEST',
	FETCH_DEVICE_LIST_SUCCESS: 'FETCH_DEVICE_LIST_SUCCESS',
	FETCH_DEVICE_LIST_ERROR: 'FETCH_DEVICE_LIST_ERROR'
};
